# Generated by Django 2.2.3 on 2019-07-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('account_name', models.CharField(max_length=200)),
                ('account_email', models.EmailField(max_length=254)),
                ('account_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('payment_method', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_cost', models.IntegerField(default=0)),
                ('item_description', models.CharField(max_length=1000)),
                ('order_notes', models.CharField(max_length=1000)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chac.Account')),
            ],
        ),
    ]
