# Generated by Django 2.2.3 on 2019-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date posted')),
                ('post_title', models.CharField(max_length=200)),
                ('post_short_text', models.CharField(max_length=500)),
                ('post_content', models.CharField(max_length=3000)),
                ('post_image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
