# Generated by Django 2.2.3 on 2019-07-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField(default=0)),
                ('assigned_date', models.DateTimeField(verbose_name='date assigned')),
                ('events', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
