# Generated by Django 2.2.3 on 2019-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=200)),
                ('assigned_date', models.DateTimeField(verbose_name='date assigned')),
                ('events', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
