# Generated by Django 2.2.3 on 2019-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0004_auto_20190731_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateField(verbose_name='date created'),
        ),
    ]
