# Generated by Django 2.2.3 on 2019-08-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0006_auto_20190731_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('account_phone', models.CharField(max_length=15)),
                ('additional_information', models.CharField(max_length=500)),
            ],
        ),
    ]
