# Generated by Django 2.2.3 on 2019-08-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0007_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_cost', models.IntegerField(default=0)),
                ('item_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasable',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='purchasable',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='purchasable',
            name='item_name',
        ),
        migrations.AddField(
            model_name='purchasable',
            name='purchased_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chac.Item'),
        ),
    ]
