# Generated by Django 2.2.3 on 2019-08-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0009_auto_20190801_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('events', models.CharField(max_length=1500)),
                ('additional_guests', models.CharField(max_length=1500)),
                ('cart', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='purchasable',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chac.User'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
