# Generated by Django 2.2.3 on 2019-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0010_auto_20190804_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ids', models.CharField(max_length=500)),
                ('total_cost', models.FloatField(default=0)),
            ],
        ),
    ]
