# Generated by Django 2.2.3 on 2019-08-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chac', '0012_auto_20190804_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
